myinvoices/models.py
from . import db, login_manager
from flask_login import UserMixin
import time


@login_manager.user_loader
def load_user(trader_id):
    return Traders.query.get(int(trader_id))
    

class Traders(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(40), unique=True, nullable=False)
    password = db.Column(db.String(80), unique=False, nullable=False)
    invoices = db.relationship('Invoices', backref='traders', lazy=True)
    
    
    def __repr__(self):
        return f'Trader("{self.email}")'
        
        
class TradeWith(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    i_trade_with = db.Column(db.String(50), unique=False, nullable=True)
    trader_id = db.Column(db.Integer, db.ForeignKey('traders.id'), nullable=False)
    
        
class Invoices(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    retailer = db.Column(db.String(20), nullable=False)
    upload_date = db.Column(db.String(10), nullable=False, default=time.strftime('%d/%m/%Y'))
    invoice = db.Column(db.String(255), unique=True, nullable=False)
    trader_id = db.Column(db.Integer, db.ForeignKey('traders.id'), nullable=False)
    
    def __repr__(self):
        return f'Invoice("{self.retailer}", "{self.upload_date}")'
        

myinvoices/main/forms.py
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import (DataRequired, Email, EqualTo, Length, \
                            ValidationError)
from flask_wtf.file import FileField, FileAllowed
from myinvoices.models import Traders
from flask_login import current_user
from flask_wtf import FlaskForm


class LoginForm(FlaskForm):
    email = StringField('', validators=[DataRequired(), Email()])
    password = PasswordField('', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Sign In')
    
    def validate_email(self, field):
        if not Traders.query.filter_by(email=field.data).first():
            raise ValidationError('You don\'t seem to be registered.')
    
            
class RegisterForm(FlaskForm):
    email = StringField('', validators=[DataRequired(), Length(1, 64), \
                                        Email()])
    password = PasswordField('', validators=[DataRequired()])
    confirm_password = PasswordField('', validators=[DataRequired(), \
                    EqualTo('password', message='Passwords must match.')])
    submit = SubmitField('Sign Up')
    
    def validate_email(self, field):
        if Traders.query.filter_by(email=field.data).first():
            raise ValidationError(
                'That email is in use. Please choose a different one.')
                
                
class UploadInvoice(FlaskForm):
    pdf_invoice = FileField(validators=[FileAllowed(['pdf'])])
    submit = SubmitField('Upload')
    
    
class AddRetailer(FlaskForm):
    retailer = StringField('Retailer', validators=[DataRequired(), Length(1, 15)])
    submit = SubmitField('Add')
    

class SearchField(FlaskForm):
    keyword = StringField('', validators=[DataRequired(), Length(1, 15)])
    submit = SubmitField('Search')

myinvoices/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail, Message
from flask_login import LoginManager
from flask_bcrypt import Bcrypt
from flask_moment import Moment
from config import config
import os

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
login_manager.login_message_category = "info"
bcrypt = Bcrypt()
moment = Moment()
mail = Mail()
db = SQLAlchemy()

basedir = os.path.abspath(os.path.dirname(__file__))

def create_app(config_name):
    app = Flask(__name__, static_url_path='/static')
    app.config.from_object(config[config_name])
    app.config['SQLALCHEMY_DATABASE_URI'] = \
                    'sqlite:///' + os.path.join(basedir, 'data.sqlite')
    app.config['UPLOAD_FOLDER'] = os.getcwd() + '/myinvoices/static/pdfs/'
    config[config_name].init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    bcrypt.init_app(app)
    from .main import main as main_blueprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(main_blueprint)
    app.register_blueprint(auth_blueprint)
    return app


if __name__ == '__main__':
    app.run()

myinvoices/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

myinvoices/main/views.py
from flask import (render_template, session, redirect, url_for, abort, \
                    request, flash, send_from_directory)
from ..models import Traders, Invoices, TradeWith
from flask_login import login_required, current_user
from .forms import UploadInvoice, AddRetailer, SearchField
from werkzeug.utils import secure_filename
import secrets, textract
from manage import app
from .. import db
from . import main
import os, time


ALLOWED_EXTENSIONS = 'pdf'
retailer_confirmed = True
matched_invoices = None
uploading_existing_invoice = False  # needs to be fixed
links = []
prompt = False

def get_retailer(pdf_file):
    pdfFile = textract.process(f"{app.config['UPLOAD_FOLDER']+pdf_file}")
    I_trade_with = TradeWith.query.filter_by(trader_id=current_user.id).all()
    for retailer in I_trade_with:
        if retailer.i_trade_with.lower() in pdfFile.decode('utf-8').lower():
            return retailer.i_trade_with


def search_invoice(key, trader_id):
    invoices = Invoices.query.filter_by(trader_id=trader_id).all()
    found_invoices = []
    for invoice in invoices:
        pdf_invoice = textract.process(f'{app.config["UPLOAD_FOLDER"]+invoice.invoice}')
        if key.lower() in pdf_invoice.decode('utf-8').lower():
            found_invoices.append(invoice.invoice)
    return found_invoices
    
    
def age_of_invoice(trader_id):
    to_delete = []
    invoices = Invoices.query.filter_by(trader_id=trader_id).all()
    for invoice in invoices:
        if int(time.strftime('%Y')) - int(invoice.upload_date[6:]) > 3:
            to_delete.append(invoice.invoice)
            
    os.chdir(f'{app.config["UPLOAD_FOLDER"]}')
    for invoice_to_delete in to_delete:
        Invoices.query.filter_by(invoice=invoice_to_delete, trader_id=trader_id).delete()
        db.session.commit()
        os.remove(invoice_to_delete)
        
    
''' COMMENTED OUT DUE TO FALSE DETECTIONS. TO BE FIXED '''

# ~ def unique_invoice(pdf_file, retailer):     
    # ~ pdfs, decisions = [], []
    # ~ encoded_pdfFile = textract.process(f"{app.config['UPLOAD_FOLDER']+pdf_file}")
    # ~ decoded_pdfFile = encoded_pdfFile.decode('utf-8').lower()
    # ~ invoices = Invoices.query.filter_by(retailer=retailer, trader_id=current_user.id).all()
    # ~ for i in invoices:
        # ~ encoded_pdf = textract.process(f"{app.config['UPLOAD_FOLDER']+pdf_file}")
        # ~ decoded_pdf = encoded_pdf.decode('utf-8').lower()
        # ~ pdfs.append(decoded_pdf)
    
    # ~ for pdf in pdfs:
        # ~ if decoded_pdfFile == pdf:
            # ~ decisions.append('identical invoice found')
        # ~ else:
            # ~ decisions.append('ok')
    
    # ~ return False if 'identical invoice found' in decisions else True
        

@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/logged_in/invoice/<invoice>')
@login_required
def display_pdf(invoice):
    if invoice:
        return send_from_directory('static/pdfs', invoice)

        
@main.route('/logged_in/close_account/<trader_id>')
@login_required
def close_account(trader_id):
    os.chdir(f'{app.config["UPLOAD_FOLDER"]}')
    invoices = Invoices.query.filter_by(trader_id=trader_id).all()
    for invoice in invoices:
        os.remove(invoice.invoice)
    
    Invoices.query.filter_by(trader_id=trader_id).delete()
    TradeWith.query.filter_by(trader_id=trader_id).delete()
    Traders.query.filter_by(id=trader_id).delete()
    db.session.commit()
    flash('Your account has been closed.', 'info')
    return redirect(url_for('auth.login'))
    
        
        
@main.route('/logged_in/delete_retailer/', defaults={'retailer': None}, methods=['GET', 'POST'])
@main.route('/logged_in/delete_retailer/<retailer>', methods=['GET', 'POST'])
@login_required
def delete_retailer(retailer):
    if retailer:
        os.chdir(f'{app.config["UPLOAD_FOLDER"]}')
        for invoice in Invoices.query.filter_by(retailer=retailer, trader_id=current_user.id).all():
            os.remove(invoice.invoice)
        TradeWith.query.filter_by(i_trade_with=retailer, trader_id=current_user.id).delete()
        Invoices.query.filter_by(retailer=retailer, trader_id=current_user.id).delete()
        db.session.commit()
    return redirect(url_for('main.interface'))
        
    
@main.route('/logged_in/', defaults={'retailer': None}, methods=['GET', 'POST'])
@main.route('/logged_in/<retailer>', methods=['GET', 'POST'])
@login_required
def interface(retailer):
    age_of_invoice(current_user.id)
    nudge_is_on = False
    no_invoices_from_this_retailer = None
    retailers = TradeWith.query.filter_by(trader_id=current_user.id).all()
    invoices = Invoices.query.filter_by(retailer=retailer, 
                    trader_id=current_user.id).all()
    
    if retailer and len(invoices) == 0:
        no_invoices_from_this_retailer = True
        
    if retailer:
        global matched_invoices
        # ~ global uploading_existing_invoice
        # ~ uploading_existing_invoice = False
        matched_invoices = None
    form1 = AddRetailer(prefix='form1')
    form2 = UploadInvoice(prefix='form2')
    form3 = SearchField(prefix='form3')
    if retailer is None:
        nudge_is_on = True
    
    if request.method == 'POST' and form1.validate_on_submit():
        new_retailer = TradeWith(i_trade_with=form1.retailer.data,
                                    trader_id=current_user.id)
        db.session.add(new_retailer)
        db.session.commit()
        global retailer_confirmed
        global prompt
        global links
        if len(links) > 0:
            del links[:]
        matched_invoices = None
        prompt = False
        retailer_confirmed = True
        return redirect(url_for('main.interface'))

    elif request.method == 'POST' and form2.validate_on_submit():
        if 'form2-pdf_invoice' not in request.files:
            flash('No file added.')
            return redirect(url_for('interface'))
        file = request.files['form2-pdf_invoice']
        if file.filename == '':
            flash('No selected file')
            return redirect(request.url)
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            filename = secrets.token_hex(2) + filename
            invoice = Invoices()
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
            invoice.retailer = get_retailer(filename)
            invoice.invoice = filename
            if not invoice.retailer:
                retailer_confirmed = False
                prompt = True
            else:
                prompt = False
            
            matched_invoices = None
            if len(links) > 0:
                del links[:]
            if retailer_confirmed:
                invoice.trader_id = current_user.id
                db.session.add(invoice)
                db.session.commit()
                flash('Invoice added.', 'success')
            else:
                os.chdir(app.config['UPLOAD_FOLDER'])
                os.remove(filename)
                return redirect(url_for('main.interface'))
            return redirect(url_for('main.interface'))
    elif request.method == 'POST' and form3.validate_on_submit():
        matched_invoices = search_invoice(form3.keyword.data, 
                                        trader_id=current_user.id)
        return redirect(url_for('main.interface'))
    
    else:
        return render_template('trader_interface.html', 
            retailers=retailers, invoices=invoices, form1=form1, 
            prompt=prompt, form2=form2, form3=form3, 
            nudge_is_on=nudge_is_on, matched_invoices=matched_invoices, 
            no_invoices_from_this_retailer=no_invoices_from_this_retailer,
            uploading_existing_invoice=uploading_existing_invoice)


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS
    
    
    
    

myinvoices/templates/about.html
{% extends 'base.html' %}

{% block head %}
    {{ super() }}
    <style>
        .container {margin-top: 60px; text-align:left;}
        p {font-size: 20px; display: block;font-family: 'Ubuntu', sans-serif;}
    </style>
{% endblock %}

{% block body %}
<div class='container'>
<a href='{{ url_for("auth.login") }}' class='btn btn-info btn-sm' style='position:absolute;top:5px;left:10px;'>Back</a>
<p>This service was designed to be privacy-minded. Thankfully, online privacy is becoming increasingly popular on the modern Internet
and this site proudly supports the idea. This site <u>keeps no identifiable information about traders</u> nor it sells it to third-parties.</p>
<p>Below is a video with Gabriel Weinberg where you can learn more about online privacy.</p>
<iframe src="https://player.vimeo.com/video/251069654" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>

<p>Website created by <a href='https://www.linkedin.com/in/marek-alexa-6408bb170/' target='_blank'>Marek Alexa</a></p>
</div>
{% endblock %}

myinvoices/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='stylesheet.css') }}" type='text/css'>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% endblock %}
    {% if title %}
    <title>MyInvoices | {{ title }}</title>
    {% else %}
    <title>MyInvoices</title>
    {% endif %}
    
  </head>
  <body>
    {% block body %}{% endblock %}
       
    
  </body>
</html>

myinvoices/templates/display_pdf.html
{% extends 'base.html' %}

{% block content %}
<img src='{{ invoice }}'>
{% endblock %}

myinvoices/templates/flashes.html
<div class='container' style='width: 300px;'>
{% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class='alert alert-{{ category }}'>
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
{% endwith %}
</div>

myinvoices/templates/index.html
{% extends 'base.html' %}

{% block body %}

    {% if title == 'Sign In' or title == 'Sign Up' %}
        <body class='text-center'>
    {% endif %}
    <a href='{{ url_for("about") }}' class='btn btn-info btn-sm' style='position:absolute;top:5px;right:10px;'>About</a>
    <div class='container' style='width: 150px;margin-top: 100px;'>
        {% include 'logo.html' %}
        
        <form class="form-signin" method='post' action=''>
            {{ form.hidden_tag() }}
          <fieldset class='form-group'>
              <div class='form-group'>
                  <label for="inputEmail" class="sr-only">Enter your email</label>
                  {% if form.email.errors %}
                    {{ form.email(class='form-control form-control-lg is-invalid') }}
                    <div class='invalid-feedback'>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class='form-control', placeholder='@', id='inputEmail', autofocus='autofocus') }}
                  {% endif %}
              </div>
                  <div class='form-group'>
                      <label for="inputPassword" class="sr-only">Password</label>
                      {% if form.password.errors %}
                        {{ form.password(class='form control form-control-lg is-invalid') }}
                        <div class='invalid-feedback'>
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                      {% else %}
                        {{ form.password(class='form-control', placeholder='Password', id='inputPassword') }}
                      {% endif %}
                        
                  <div class="checkbox mb-3"><br>
                    {{ form.remember(class='form-check-input') }}
                    {{ form.remember.label(class='form-check-label') }}
                  </div>
                </div>
          </fieldset>
          <div class='form-group'>
          {{ form.submit(class='btn btn-primary btn-lg') }}
          </div>
          {% include 'flashes.html' %}
          <small class='text-muted'>Haven't got an account ? <a href='{{ url_for("register") }}'>Sign Up</a></small>
          <p class="mt-5 mb-3 text-muted">Created by Marek Alexa</p>
        </form>
    </div>
{% endblock %}

myinvoices/templates/logo.html
<img src='{{ url_for("static", filename="database_icon.png") }}'><p id='my_invoices_logo'>MyInvoices</p>

myinvoices/templates/register.html
{% extends 'base.html' %}

{% block head %}
    {{ super() }}
    <style>
        .container {margin-top: 100px; width: 150px;}
    </style>
{% endblock %}

{% block body %}
<div class='row'>
    <div class='col-md-4'></div>
    <div class='col-md-4'>
        <div class='container' style='width:320px;'>
        {% include 'flashes.html' %}
        {% include 'logo.html' %}
        <form method='post' action=''>
            {{ form.hidden_tag() }}
            <fieldset class='form-group'>
                <div class='form-group'>
                  <label for="inputEmail" class="sr-only">Enter your email</label>
                  {% if form.email.errors %}
                    {{ form.email(class='form-control form-control-lg is-invalid') }}
                    <div class='invalid-feedback'>
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.email(class='form-control mb-3', placeholder='@', id='inputEmail', autofocus='autofocus') }}
                  {% endif %}
                  
                  {% if form.password.errors %}
                    {{ form.password(class='form-control form-control-lg is-invalid') }}
                    <div class='invalid-feedback'>
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.password(class='form-control mb-3', placeholder='Password') }}
                  {% endif %}
                  
                  {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class='form-control form-control-lg is-invalid') }}
                    <div class='invalid-feedback'>
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                  {% else %}
                    {{ form.confirm_password(class='form-control mb-3', placeholder='Confirm Password') }}
                  {% endif %}
            </div>
            </fieldset>
            
            <div class='form-group'>
                {{ form.submit(class='btn btn-primary btn-lg') }}
            </div>
        </form>
        
        <p class='on-bottom'>Got An Account ? <a href='{{ url_for("auth.login") }}'>Sign In</a> instead !</p>
    </div>
    </div>
    
    <div class='col-md-4'><a id='about_btn' href='{{ url_for("main.about") }}'>Your Privacy First</a></div>
</div>

{% endblock %}

myinvoices/templates/trader_interface.html
{% extends 'base.html' %}

{% block body %}

{% if retailers %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">{{ current_user.email }}</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        {% for retail in retailers %}
        <li class="nav-item active">
          <a class="nav-link" href='{{ url_for("main.interface", retailer=retail.i_trade_with) }}'>{{ retail.i_trade_with }}</a>
        </li>
        {% endfor %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span style='color: red;'>delete retailer</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% for retail in retailers %}
         <a class="dropdown-item" href='{{ url_for("main.delete_retailer", retailer=retail.i_trade_with) }}'>{{ retail.i_trade_with }}</a>
        {% endfor %}
        <div class="dropdown-divider"></div>
         <a class="dropdown-item" href='{{ url_for("main.close_account", trader_id=current_user.id) }}'>Close Account</a>
        </div>
        
      </li>
    
    </ul>
    <form method='post' class="form-inline my-2 my-lg-0" action=''>
      <div class='form-group'>
         {{ form3.hidden_tag() }}
         {{ form3.keyword(class="form-control mr-sm-2", placeholder="Search by item, total price") }}
      </div>
         {{ form3.submit(class="btn btn-outline-success my-2 my-sm-0") }}
    </form>
    
    <a class="nav-link" href='{{ url_for("auth.logout") }}'>Logout</a>
  </div>
</nav>
{% else %}
    <p style='margin-top:20px;'>You have no saved invoices. Start adding on the right.</p>
        
{% endif %}

{% if nudge_is_on and retailers %}
    <hr>
    <p>Tap / Click on business to see invoices.</p>
    <hr>
{% endif %}
<div class='row' style='margin-top: 10px;'>
    <div class='col-md-2' style='margin-left: 5px;'>
        
            <div class='form-group'>
            <form method='post' action='' enctype='multipart/form-data' style='margin-bottom: 20px;'>
                {{ form2.hidden_tag() }}
                {{ form2.pdf_invoice(class='form-control mb-3') }}
            </div>
            <div class='form-group'>
                {{ form2.submit(class='btn btn-info') }}
            </div>
            </form>
            <hr>
            <div class='alert alert-info'>Invoices older than 3 years are being automatically erased.</div>
            {% include 'flashes.html' %}
            {% if uploading_existing_invoice %}
            <div class='alert alert-warning'><b>This invoice already exists.</b></div>
            {% endif %}
    </div>
    <div class='col-md-7'>
                  
        {% if no_invoices_from_this_retailer %}
            <div class='alert alert-info'>You haven't got any invoices from this retailer yet.</div>
        {% elif matched_invoices %}
            <p><u>Found invoices:</u></p>
            <table class="table">
              <tbody>
                {% for invoice in matched_invoices %}
                    <tr>
                        <td><a href='{{ url_for("main.display_pdf", invoice=invoice, _external=True) }}'>{{ invoice }}</a></td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
            
        {% elif invoices %}
            <table class="table">
              <tbody>
                {% for invoice in invoices %}
                    <tr>
                      <th scope="row"></th>
                        <td>{{ invoice.retailer }}</td>
                        <td><a href='{{ url_for("main.display_pdf", invoice=invoice.invoice, _external=True) }}'>{{ invoice.invoice[4:] }}</a></td>
                    </tr>
                {% endfor %}
              </tbody>
            </table>
                    
        {% endif %}
    </div>
    <div class='col-md-2'>
        {% if prompt %}
            <div class='alert alert-warning'>This retailer isn't in your list of retailers. <b>Add it first</b>.</div>
        {% endif %}
        <div class='container' style='width: 10em;'>
            <form method='post' action=''>
                {{ form1.hidden_tag() }}
                <div class='form-group'>
                {% if form1.retailer.errors %}
                    {{ form1.retailer(class='form-control form-control-lg is-invalid') }}
                    <div class='invalid-feedback'>
                        <span>{{ error }}</span>
                    </div>
                
                {% else %}
                    {{ form1.retailer(class='form-control', placeholder='Add Retailer') }}
                {% endif %}
                </div>
                <div class='form-group'>
                    {{ form1.submit(class='btn btn-primary') }}
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}